### ISSUE TITLE
CoachView can't see the team member's desktop, only black screen

### ISSUE THREAD

**Issue by li1553770945** [icpctools/icpctools#681] opened 2022-10-04 09:58 UTC
I have two computer, the operating system of them is windows10, and both of them have the software VLC. My domjudege is runing on the Cloud Servers, the CDS is runing on the computer A, whose ip is "192.168.1.193". I used the command `vlc -I dummy -q screen:// --screen-fps=30 --sout "#transcode{venc=x264{keyint=15},vcodec=h264,vb=0}:http{mux=ts,dst=:9090/}"` on computer A to start a stream of desktop.  

When I open the vlc on computer B and start playing the screen of computer A, it is normal.

![image](https://user-images.githubusercontent.com/55867654/193791246-71133659-df62-4807-a243-68b926122711.png)

But When I start coachview on computer B, it connect to the CDS correctly, but when I try to see the desktop, it's just show me a black screen.

![1A $8{1F}LQB@62)K__O__M](https://user-images.githubusercontent.com/55867654/193790427-5aa2d8fc-041f-4962-9e41-85a24bede1f7.png)

**Comment by deboer-tim** [comment] 2022-10-04 12:33
Can you access the video feed directly through the CDS (i.e. without coach view)? You should be able to see the URL by visiting the team endpoint (https://192.168.1.193/api/contests/<id>/teams/2) and looking at the desktop property (e.g. "desktop":[{"href":"http:///192.168.1.193/stream/0","mime":"application/m2ts"}])

The URL listed should be something like http://192.168.1.193/stream/0, try accessing that directly with VLC. If it works then we know the problem is in the coach view and we'll look at the logs next (look for latest file in coach view /logs folder and attach here); if not then it is a CDS/config issue.

**Comment by li1553770945** [comment] 2022-10-04 13:14
> Can you access the video feed directly through the CDS (i.e. without coach view)? You should be able to see the URL by visiting the team endpoint (https://192.168.1.193/api/contests//teams/2) and looking at the desktop property (e.g. "desktop":[{"href":"http:///192.168.1.193/stream/0","mime":"application/m2ts"}])
> 
> The URL listed should be something like http://192.168.1.193/stream/0, try accessing that directly with VLC. If it works then we know the problem is in the coach view and we'll look at the logs next (look for latest file in coach view /logs folder and attach here); if not then it is a CDS/config issue.

I tried the url `https://192.168.1.193:8443/api/contests/6/teams/2`, it shows the correct data:

![image](https://user-images.githubusercontent.com/55867654/193821451-3b48c727-081f-46bb-b79b-d090fdfba81a.png)

When I tried the url in VLC on another computer, it aslo displayed the screen correctly.
![S{BJ76%UV(~F{MBA$@B7~KJ](https://user-images.githubusercontent.com/55867654/193828002-87e3c817-6352-458e-8fdb-f6ae5cfc3a44.png)


 But when I tried the CoachView, it showed still the black screen, same as before.

![1A $8{1F}LQB@62)K__O__M](https://user-images.githubusercontent.com/55867654/193828049-2c5e1ae3-c526-423a-a545-5a8a08e61749.png)


I have uploaded the log file.

[coachView_22.10.04_21.09.44.log](https://github.com/icpctools/icpctools/files/9707141/coachView_22.10.04_21.09.44.log)

**Comment by deboer-tim** [comment] 2022-10-05 20:50
Sorry, I've confirmed there is a minor bug in the coach view (fix released) that would have stopped it trying to pull video.

Unfortunately, the VLCJ library that's being used for video also appears to not support Java 17. I am trying to setup a test system so that I can confirm and try a newer version of the library.

**Comment by li1553770945** [comment] 2022-10-06 09:05
I tried to change my java version to java 11 and now it works fine, thanks!

**Comment by deboer-tim** [comment] 2022-10-21 17:09
I've confirmed this, updated to the latest VLJC, and confirmed it now works on Java 17 as well. Thank you, closing!

**Closed by deboer-tim** 2022-10-21 17:09 UTC
