### ISSUE TITLE
Add CDS support for synching with API

### ISSUE THREAD

**Issue by niemela** [icpctools/icpctools#550] opened 2021-10-18 22:41 UTC
Add some way to manually trigger the CDS to synch the data from the API endpoints (not the event feed).

**Comment by deboer-tim** [comment] 2022-05-09 16:49
If a client error causes it to get out of sync with the provider, the solution has always been to throw out any cache and/or restart. If the problem is the provider failed to send an event there were two spec-supported options: 1) 'resend' an event, or 2) throw out any cache, invalidate ids, and restart the feed. The core problem is that you have to know what was missing for the first option, and the second is fairly heavy-handed.

As both a provider and consumer, the CDS already supported all of these options, and has an admin UI where you can manually inject any event, or restart/reset the client-side feed. So to me this request was covering the middle ground: maybe we think something was missing in the feed but don't know what, and the provider can't fix it or doesn't want to (or can't) restart the entire feed. So this is a valid request that would provide an additional option for the CDS to sync with a provider.

Enter the new Contest API spec. Providers can now send an entire endpoint as one notification, effectively triggering this exact same sync with any/all clients at any time. This is a better solution to the problem since it helps all clients and doesn't require any additional support beyond the spec, hence I'm going to close this request. If you disagree please feel free to reopen (and we should probably discuss on a CLICS call).

The only drawback is that the provider needs to support and decide when to trigger this. Maybe it should be called out in the spec, but IMHO this should be part of any provider's (including the CDS') failure-recovery plan.

FWIW, PR #642 just added client-side support for the new feed to all of the ICPC Tools, and they're still compatible with the previous feed format.

**Closed by deboer-tim** 2022-05-09 16:49 UTC
Labels: enhancement, area/CDS
